name: translation_tool
description: A Flutter translation tool library based on Google Translate API with memory and local caching support.
version: 1.0.2
repository: https://github.com/AChloe/translation_tool

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
