name: danmaku_widget
description: A Flutter widget for displaying animated danmaku (bullet comments) with customizable styles and effects.
version: 1.0.4
homepage: https://github.com/your-username/danmaku_widget

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  visibility_detector_widget: ^1.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
