name: app_socket_io
description: A Flutter Socket.IO connection management library based on socket_io_client with automatic reconnection and message queuing.
version: 1.0.3
repository: https://github.com/app_socket_io/


environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: 1.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0