name: smart_video_player
description: A simple video player widget for Flutter applications with enhanced playback controls and features.
version: 1.0.7
repository: https://github.com/your-username/smart_video_player

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.10.0
  video_player_android: ^2.8.4
  chewie: ^1.11.3
  audio_session: ^0.2.2
  visibility_detector_widget: ^1.0.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
