name: image_loader_tool
description: A simple image loading tool.
version: 1.0.3
repository: https://github.com/image_loader_tool

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
