name: app_ui
description: A collection of reusable UI components and widgets for Flutter applications.
version: 1.2.4
repository: https://github.com/tree_packages/main/tree/app_ui

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text_plus: ^3.0.2
  extended_tabs: ^5.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
